

```{r}
library(psych)
data <- read.csv("C:/Users/10331/OneDrive/Desktop/TrainingSet.csv")
names(data)[1] <- "Country_Name"
data$Country_Name <- as.character(data$Country_Name)
data$Country_Name <- data$Country.Name
a <- 1:37
b <- 40
data2 <- subset(data, select = c(a,b))
names(data2)[2:37] <- c(1972:2007)
str(data2)
```
```{r}
library(reshape)
mdata <- melt(data2, id=c("Country_Name","Series.Name"))
```

```{r}
names(mdata)[3] <- "Year"
mdata
```
```{r}
table <- cast(mdata,Year + Country_Name ~ Series.Name)
table 
```

```{r}
listn<- data.frame("Name"=character(),"Num"=integer())
counter <- 0
for (cname in unique(data$Country_Name)){
  counter = counter +1
  temp <- table$Country_Name == cname
  count <- sum(is.na(table[temp,]))
  listn[counter,"Name"]<-cname
  listn[counter,"Num"]<-count
}
```

```{r}
library(plyr)
listn <- head(arrange(listn,Num), n = 10)
listn
```

```{r}
df <- table[0,]
for (cname in listn$Name){
  crita <- table$Country_Name == cname
  temp <- table[crita,]
  df<-rbind (df,temp)
}
df
```

```{r}
df1 <- df[,colSums(is.na(df)) == 0]
df1
```

```{r}
listl <- data.frame("Name"=character(),"Num"=integer())
for (item in names(df1)){
  crita <- df1[item] == 0
  temp <- data.frame("Name"=item,"Num"=sum(crita))
  listl<-rbind(listl,temp)
}
df1 <- df1[,listl[(listl$Num == 0),"Name"]]
df1
```

```{r}
lista <- names(df1)
lista <- lista [c(94,85,135,136,153,244,245,29,146,149)]
lista
```
```{r}
df1 <- df1[, lista]
```

```{r}
Mexico <- df1[1:36,]
Philippines <- df1[37:72,]
Morocco <- df1[73:108,]
Peru <- df1[109:144,]
Indonesia <- df1[145:180,]
Colombia <- df1[181:216,]
CostaRica <- df1[217:252,]
Venezuela <- df1[253:288,]
Tunisia <- df1[289:324,]
Ecuador <- df1[325:360,]

rownames(Mexico) <- c(1972:2007)
rownames(Philippines) <- c(1972:2007)
rownames(Morocco) <- c(1972:2007)
rownames(Peru) <- c(1972:2007)
rownames(Indonesia) <- c(1972:2007)
rownames(Colombia) <- c(1972:2007)
rownames(CostaRica) <- c(1972:2007)
rownames(Venezuela) <- c(1972:2007)
rownames(Tunisia) <- c(1972:2007)
rownames(Ecuador) <- c(1972:2007)

Mexico
Philippines
Morocco
Peru
Indonesia
Colombia
CostaRica
Venezuela
Tunisia
Ecuador
```
```{r}
describe(Mexico)
describe(Philippines)
describe(Morocco)
describe(Peru)
describe(Indonesia)
describe(Colombia)
describe(CostaRica)
describe(Venezuela)
describe(Tunisia)
describe(Ecuador)
```
```{r}
pairs(Mexico)
c<-cor(Mexico)
library(ggcorrplot)
ggcorrplot(c)
```
```{r}
pairs(Philippines)
c<-cor(Philippines)
library(ggcorrplot)
ggcorrplot(c)
```
```{r}
pairs(Morocco)
c<-cor(Morocco)
library(ggcorrplot)
ggcorrplot(c)
```

```{r}
pairs(Peru)
c<-cor(Peru)
library(ggcorrplot)
ggcorrplot(c)
```

```{r}
pairs(Indonesia)
c<-cor(Indonesia)
library(ggcorrplot)
ggcorrplot(c)
```

```{r}
pairs(Colombia)
c<-cor(Colombia)
library(ggcorrplot)
ggcorrplot(c)
```

```{r}
pairs(CostaRica)
c<-cor(CostaRica)
library(ggcorrplot)
ggcorrplot(c)
```

```{r}
pairs(Venezuela)
c<-cor(Venezuela)
library(ggcorrplot)
ggcorrplot(c)
```

```{r}
pairs(Tunisia)
c<-cor(Tunisia)
library(ggcorrplot)
ggcorrplot(c)
```
```{r}
pairs(Ecuador)
c<-cor(Ecuador)
library(ggcorrplot)
ggcorrplot(c)
```

```{r}
library(ggplot2)

gdata <- data.frame(Mexico)
names(gdata) <- c("GDP","Food","Life-F","Life-M","Infant","65-F","65-M","CO2","Exports","Import")
gdata<-scale(gdata)
gdata <- as.data.frame.table(gdata)
names(gdata) <- c("Year","Indicator","Value")
ggplot(gdata, aes(Year, Value,group=Indicator)) + geom_line(aes(color=Indicator))
```

```{r}
gdata <- data.frame(Philippines)
names(gdata) <- c("GDP","Food","Life-F","Life-M","Infant","65-F","65-M","CO2","Exports","Import")
gdata<-scale(gdata)
gdata <- as.data.frame.table(gdata)
names(gdata) <- c("Year","Indicator","Value")
ggplot(gdata, aes(Year, Value,group=Indicator)) + geom_line(aes(color=Indicator))
```

```{r}
gdata <- data.frame(Morocco)
names(gdata) <- c("GDP","Food","Life-F","Life-M","Infant","65-F","65-M","CO2","Exports","Import")
gdata<-scale(gdata)
gdata <- as.data.frame.table(gdata)
names(gdata) <- c("Year","Indicator","Value")
ggplot(gdata, aes(Year, Value,group=Indicator)) + geom_line(aes(color=Indicator))
```
```{r}
gdata <- data.frame(Peru)
names(gdata) <- c("GDP","Food","Life-F","Life-M","Infant","65-F","65-M","CO2","Exports","Import")
gdata<-scale(gdata)
gdata <- as.data.frame.table(gdata)
names(gdata) <- c("Year","Indicator","Value")
ggplot(gdata, aes(Year, Value,group=Indicator)) + geom_line(aes(color=Indicator))
```
```{r}
gdata <- data.frame(Indonesia)
names(gdata) <- c("GDP","Food","Life-F","Life-M","Infant","65-F","65-M","CO2","Exports","Import")
gdata<-scale(gdata)
gdata <- as.data.frame.table(gdata)
names(gdata) <- c("Year","Indicator","Value")
ggplot(gdata, aes(Year, Value,group=Indicator)) + geom_line(aes(color=Indicator))
```
```{r}
gdata <- data.frame(Colombia)
names(gdata) <- c("GDP","Food","Life-F","Life-M","Infant","65-F","65-M","CO2","Exports","Import")
gdata<-scale(gdata)
gdata <- as.data.frame.table(gdata)
names(gdata) <- c("Year","Indicator","Value")
ggplot(gdata, aes(Year, Value,group=Indicator)) + geom_line(aes(color=Indicator))
```
```{r}
gdata <- data.frame(CostaRica)
names(gdata) <- c("GDP","Food","Life-F","Life-M","Infant","65-F","65-M","CO2","Exports","Import")
gdata<-scale(gdata)
gdata <- as.data.frame.table(gdata)
names(gdata) <- c("Year","Indicator","Value")
ggplot(gdata, aes(Year, Value,group=Indicator)) + geom_line(aes(color=Indicator))
```
```{r}
gdata <- data.frame(Venezuela)
names(gdata) <- c("GDP","Food","Life-F","Life-M","Infant","65-F","65-M","CO2","Exports","Import")
gdata<-scale(gdata)
gdata <- as.data.frame.table(gdata)
names(gdata) <- c("Year","Indicator","Value")
ggplot(gdata, aes(Year, Value,group=Indicator)) + geom_line(aes(color=Indicator))
```
```{r}
gdata <- data.frame(Tunisia)
names(gdata) <- c("GDP","Food","Life-F","Life-M","Infant","65-F","65-M","CO2","Exports","Import")
gdata<-scale(gdata)
gdata <- as.data.frame.table(gdata)
names(gdata) <- c("Year","Indicator","Value")
ggplot(gdata, aes(Year, Value,group=Indicator)) + geom_line(aes(color=Indicator))
```
```{r}
gdata <- data.frame(Ecuador)
names(gdata) <- c("GDP","Food","Life-F","Life-M","Infant","65-F","65-M","CO2","Exports","Import")
gdata<-scale(gdata)
gdata <- as.data.frame.table(gdata)
names(gdata) <- c("Year","Indicator","Value")
ggplot(gdata, aes(Year, Value,group=Indicator)) + geom_line(aes(color=Indicator))
```